# Peaky Blinders IMDb Ratings, Part III

Following this <a href="https://www.dataquest.io/blog/web-scraping-beautifulsoup/">tutorial</a> on scraping IMDb with Beautiful Soup.

In [3]:
# Scraping goal, to pull....
# tconst value in URL
# Parent tconst 
# Season #
# Episode #
# Average vote out of 10

In [5]:
from requests import get
url = 'http://www.imdb.com/search/title?release_date=2017&sort=num_votes,desc&page=1'
response = get(url)
print(response.text[:500])

<!DOCTYPE html>
<html
    xmlns:og="http://ogp.me/ns#"
    xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="apple-itunes-app" content="app-id=342792525, app-argument=imdb:///?src=mdot">



        <script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>

<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle"

In [6]:
from bs4 import BeautifulSoup
html_soup = BeautifulSoup(response.text, 'html.parser')
type(html_soup)

bs4.BeautifulSoup

In [10]:
movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
print(type(movie_containers))
print(len(movie_containers))

<class 'bs4.element.ResultSet'>
50

In [16]:
first_movie = movie_containers[0]
first_movie

<div class="lister-item mode-advanced">
<div class="lister-top-right">
<div class="ribbonize" data-caller="filmosearch" data-tconst="tt3315342"></div>
</div>
<div class="lister-item-image float-left">
<a href="/title/tt3315342/"> <img alt="Logan" class="loadlate" data-tconst="tt3315342" height="98" loadlate="https://m.media-amazon.com/images/M/MV5BYzc5MTU4N2EtYTkyMi00NjdhLTg3NWEtMTY4OTEyMzJhZTAzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX67_CR0,0,67,98_AL_.jpg" src="https://m.media-amazon.com/images/G/01/imdb/images/nopicture/large/film-184890147._CB466725069_.png" width="67"/>
</a> </div>
<div class="lister-item-content">
<h3 class="lister-item-header">
<span class="lister-item-index unbold text-primary">1.</span>
<a href="/title/tt3315342/">Logan</a>
<span class="lister-item-year text-muted unbold">(2017)</span>
</h3>
<p class="text-muted">
<span class="certificate">18A</span>
<span class="ghost">|</span>
<span class="runtime">137 min</span>
<span class="ghost">|</span>
<span class="genre">
Action, Drama, Sci-Fi            </span>
</p>
<div class="ratings-bar">
<div class="inline-block ratings-imdb-rating" data-value="8.1" name="ir">
<span class="global-sprite rating-star imdb-rating"></span>
<strong>8.1</strong>
</div>
<div class="inline-block ratings-user-rating">
<span class="userRatingValue" data-tconst="tt3315342" id="urv_tt3315342">
<span class="global-sprite rating-star no-rating"></span>
<span class="rate" data-no-rating="Rate this" data-value="0" name="ur">Rate this</span>
</span>
<div class="starBarWidget" id="sb_tt3315342">
<div class="rating rating-list" data-auth="" data-ga-identifier="" data-starbar-class="rating-list" data-user="" id="tt3315342|imdb|8.1|8.1|adv_li_tt||advsearch|title" itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating" title="Users rated this 8.1/10 (612,536 votes) - click stars to rate">
<meta content="8.1" itemprop="ratingValue"/>
<meta content="10" itemprop="bestRating"/>
<meta content="612536" itemprop="ratingCount"/>
<span class="rating-bg"> </span>
<span class="rating-imdb" style="width: 113.4px"> </span>
<span class="rating-stars">
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>1</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>2</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>3</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>4</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>5</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>6</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>7</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>8</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>9</span></a>
<a href="/register/login?why=vote" rel="nofollow" title="Register or login to rate this title"><span>10</span></a>
</span>
<span class="rating-rating"><span class="value">8.1</span><span class="grey">/</span><span class="grey">10</span></span>
<span class="rating-cancel"><a href="/title/tt3315342/vote?v=X;k=" rel="nofollow" title="Delete"><span>X</span></a></span>
 </div>
</div>
</div>
<div class="inline-block ratings-metascore">
<span class="metascore favorable">77        </span>
        Metascore
            </div>
</div>
<p class="text-muted">
    In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.</p>
<p class="">
    Director:
<a href="/name/nm0003506/">James Mangold</a>
<span class="ghost">|</span>
    Stars:
<a href="/name/nm0413168/">Hugh Jackman</a>,
<a href="/name/nm0001772/">Patrick Stewart</a>,
<a href="/name/nm6748436/">Dafne Keen</a>,
<a href="/name/nm2933542/">Boyd Holbrook</a>
</p>
<p class="sort-num_votes-visible">
<span class="text-muted">Votes:</span>
<span data-value="612536" name="nv">612,536</span>
<span class="ghost">|</span> <span class="text-muted">Gross:</span>
<span data-value="226,277,068" name="nv">$226.28M</span>
</p>
</div>
</div>

In [22]:
first_name = first_movie.h3.a.text
first_name

'Logan'

In [25]:
first_year = first_movie.h3.find('span', class_='lister-item-year text-muted unbold').text
first_year

'(2017)'

In [30]:
first_rating = float(first_movie.strong.text)
first_rating

8.1

In [35]:
first_mscore = int(first_movie.find('span', class_='metascore').text)
first_mscore

77

In [43]:
first_votes = int(first_movie.find('span', attrs = {'name':'nv'})['data-value'])
first_votes

612536

In [45]:
movie_tconst = first_movie.find('span', class_='userRatingValue')['data-tconst']
movie_tconst

'tt3315342'

In [46]:
# Create lists to score the scraped data
movie_names = []
movie_year = []
imdb_ratings = []
votes = []
movie_tconst = []

In [47]:
# Extra data from each movie container
for container in movie_containers:
    # Movie name
    name = container.h3.a.text
    movie_names.append(name)
    
    # Movie year
    year = container.h3.find('span', class_='lister-item-year text-muted unbold').text
    movie_year.append(year)
    
    # Movie IMDb Rating
    rating = float(container.strong.text)
    imdb_ratings.append(rating)
    
    # Number of votes
    vote = int(container.find('span', attrs = {'name':'nv'})['data-value'])
    votes.append(vote)
    
    # Movie tconst
    the_tconst = container.find('span', class_='userRatingValue')['data-tconst']
    movie_tconst.append(the_tconst)

In [48]:
# Use Pandas to chart out the lists 
import pandas as pd

In [51]:
test_df = pd.DataFrame({'movie': movie_names,
                        'year': movie_year,
                        'imdb': imdb_ratings,
                        'votes': votes,
                        'tconst': movie_tconst})
print(test_df.info())
test_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
movie     50 non-null object
year      50 non-null object
imdb      50 non-null float64
votes     50 non-null int64
tconst    50 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 2.1+ KB
None

,movie,year,imdb,votes,tconst
0,Logan,(2017),8.1,612536,tt3315342
1,Thor: Ragnarok,(2017),7.9,547661,tt3501632
2,Guardians of the Galaxy Vol. 2,(2017),7.6,536382,tt3896198
3,Star Wars: Episode VIII - The Last Jedi,(2017),7.0,535054,tt2527336
4,Wonder Woman,(2017),7.4,525383,tt0451279
5,Dunkirk,(2017),7.9,514006,tt5013056
6,Spider-Man: Homecoming,(2017),7.4,481473,tt2250912
7,Get Out,(I) (2017),7.7,456895,tt5052448
8,It,(I) (2017),7.3,431413,tt1396484
9,Blade Runner 2049,(2017),8.0,427375,tt1856101
10,Baby Driver,(2017),7.6,408404,tt3890160
11,"Three Billboards Outside Ebbing, Missouri",(2017),8.2,395864,tt5027774
12,Justice League,(2017),6.4,360493,tt0974015
13,The Shape of Water,(2017),7.3,347571,tt5580390
14,John Wick: Chapter 2,(2017),7.5,341287,tt4425200
15,Coco,(I) (2017),8.4,335214,tt2380307
16,Jumanji: Welcome to the Jungle,(2017),6.9,298862,tt2283362
17,Beauty and the Beast,(I) (2017),7.1,258304,tt2771200
18,Kong: Skull Island,(2017),6.6,256794,tt3731562
19,Kingsman: The Golden Circle,(2017),6.7,254927,tt4649466
20,Pirates of the Caribbean: Dead Men Tell No Tales,(2017),6.6,247964,tt1790809
21,Alien: Covenant,(2017),6.4,243181,tt2316204
22,13 Reasons Why,(2017– ),7.8,235729,tt1837492
23,La Casa de Papel,(2017– ),8.4,233879,tt6468322
24,The Greatest Showman,(2017),7.6,219305,tt1485796
25,War for the Planet of the Apes,(2017),7.4,217084,tt3450958
26,Lady Bird,(2017),7.4,215333,tt4925292
27,Murder on the Orient Express,(2017),6.5,197294,tt3402236
28,Life,(I) (2017),6.6,196692,tt5442430
29,The Fate of the Furious,(2017),6.7,195069,tt4630562
30,Wind River,(2017),7.7,188460,tt5362988
31,Call Me by Your Name,(2017),7.9,188433,tt5726616
32,Ghost in the Shell,(2017),6.3,188398,tt1219827
33,Mindhunter,(2017– ),8.6,186450,tt5290382
34,King Arthur: Legend of the Sword,(2017),6.7,182511,tt1972591
35,Mother!,(2017),6.6,178842,tt5109784
36,The Hitman's Bodyguard,(2017),6.9,176868,tt1959563
37,Dark,(2017– ),8.7,174875,tt5753856
38,The Punisher,(2017–2019),8.5,168940,tt5675620
39,"I, Tonya",(2017),7.5,166571,tt5580036
40,Atomic Blonde,(2017),6.7,166092,tt2406566
41,The Mummy,(2017),5.4,165897,tt2345759
42,Bright,(I) (2017),6.3,160667,tt5519340
43,Darkest Hour,(2017),7.4,158606,tt4555426
44,Valerian and the City of a Thousand Planets,(2017),6.5,154026,tt2239822
45,Baywatch,(2017),5.5,152345,tt1469304
46,The Handmaid's Tale,(2017– ),8.5,152250,tt5834204
47,American Made,(2017),7.1,148955,tt3532216
48,Ozark,(2017– ),8.4,146635,tt5071412
49,Big Little Lies,(2017–2019),8.5,137776,tt3920596

In [53]:
# Scrape other webpages by changing the URL
# Create list with strings that corresopnds to the first four pages
pages = [str(i) for i in range(1,5)]
pages

['1', '2', '3', '4']

In [54]:
# Create a list with strings corresponding to years 2000 to 2017
years_url = [str(i) for i in range(2000, 2018)]
years_url

['2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017']

In [55]:
# Control the crawl-rate by using sleep() to pause execution of loop
# Use randint() to imic human behaviour
from time import sleep
from random import randint

for _ in range(0,5):
    print('Blah')
    
    # Pause for (x) seconds before continuing executing the for loop
    sleep(randint(1,4))

Blah
Blah
Blah
Blah
Blah

In [60]:
# Tracking the frequency/speed of requests to make sure the program
# is not overloading the server and IP address gets banned
from time import time
from IPython.core.display import clear_output

start_time = time()
requests = 0

for _ in range(5):
    # Also track number of requests to terminate loop if # of 
    # expected requests is exeeded
    requests += 1
    
    sleep(randint(1,10))
    elapsed_time = time() - start_time
    print('Request #: {}; Frequency: {:.4f} request per second'.format(requests, requests/elapsed_time))
    
    # To only show the most recent request and frequency info
    clear_output(wait = True)

Request #: 5; Frequency: 0.1470 request per second

In [64]:
# Monitor the status of code 
# Where successful request has a status code of 200
# Issue a warning if status code is not 200
from warnings import warn
warn('Warning Simulation')

C:\Users\Fani\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Warning Simulation
  """

In [77]:
pages = [str(i) for i in range(1,3)]
years_url = [str(i) for i in range(2000,2006)]
headers = {"Accept-Language": "en-US, en;q=0.5"}

# Lists to score the scraped data
movie_names = []
movie_year = []
imdb_ratings = []
votes = []
movie_tconst = []

# To monitor the loop
start_time = time()
requests = 0

# For every year in the interval from 2000 to 2017
for year_url in years_url:
    
    # For every page from 1 to 4
    for page in pages:
        
        # Make a get request
        response = get('http://www.imdb.com/search/title?release_date=' + year_url + '&sort=num_votes,desc&page=' + page, headers=headers)
        
        # Pause the loop
        sleep(randint(8,15))
        
        # Monitor the requests
        requests += 1
        elapsed_time = time() - start_time
        print('Request #: {}; Frequency: {:.4f} request per second'.format(requests, requests/elapsed_time))
        clear_output(wait = True) 
        
        # If request is not successful, status code is not 200 so issue warning
        if response.status_code != 200:
            warn('Request: {}; Status code: {}'.format(requests, response.status_code))
        
        # Break the loop if number of requests is greater than expected
        if requests > 72:
            warn('Number of requests was greater than expected. Quitting...')
            break
            
        # Parse content of the request/webpage iwth BeautifulSoup
        html_soup = BeautifulSoup(response.text, 'html.parser')

        # Select all movie containers by div class from that page
        movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
        
        # For every movie out of 50
        for container in movie_containers:
            # Movie name
            name = container.h3.a.text
            movie_names.append(name)

            # Movie year
            year = container.h3.find('span', class_='lister-item-year text-muted unbold').text
            movie_year.append(year)

            # Movie IMDb Rating
            rating = float(container.strong.text)
            imdb_ratings.append(rating)

            # Number of votes
            vote = int(container.find('span', attrs = {'name':'nv'})['data-value'])
            votes.append(vote)

            # Movie tconst
            the_tconst = container.find('span', class_='userRatingValue')['data-tconst']
            movie_tconst.append(the_tconst)

Request #: 12; Frequency: 0.0813 request per second

In [78]:
test_df = pd.DataFrame({'movie': movie_names,
                        'year': movie_year,
                        'imdb': imdb_ratings,
                        'votes': votes,
                        'tconst': movie_tconst})
print(test_df.info())
test_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 5 columns):
movie     600 non-null object
year      600 non-null object
imdb      600 non-null float64
votes     600 non-null int64
tconst    600 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 23.6+ KB
None

                      movie         year  imdb    votes     tconst
0                 Gladiator       (2000)   8.5  1284694  tt0172495
1                   Memento       (2000)   8.4  1079990  tt0209144
2                    Snatch       (2000)   8.3   754909  tt0208092
3       Requiem for a Dream       (2000)   8.3   736361  tt0180093
4                     X-Men       (2000)   7.4   555955  tt0120903
..                      ...          ...   ...      ...        ...
595              Hard Candy       (2005)   7.1   150507  tt0424136
596          Criminal Minds  (2005–2020)   8.1   149046  tt0452046
597                    Rome  (2005–2007)   8.7   148527  tt0384766
598              Flightplan       (2005)   6.3   148424  tt0408790
599  Green Street Hooligans       (2005)   7.5   138334  tt0385002

[600 rows x 5 columns]

In [73]:
# Where his code differs from mine
pages = [str(i) for i in range(1,3)]
years_url = [str(i) for i in range(2000,2006)]
headers = {"Accept-Language": "en-US, en;q=0.5"}

# Redeclaring the lists to store data in
names = []
years = []
imdb_ratings = []
metascores = []
votes = []

# Preparing the monitoring of the loop
start_time = time()
requests = 0

# For every year in the interval 2000-2017
for year_url in years_url:

    # For every page in the interval 1-4
    for page in pages:

        # Make a get request
        response = get('http://www.imdb.com/search/title?release_date=' + year_url +
        '&sort=num_votes,desc&page=' + page, headers = headers)

        # Pause the loop
        sleep(randint(8,15))

        # Monitor the requests
        requests += 1
        elapsed_time = time() - start_time
        print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
        clear_output(wait = True)

        # Throw a warning for non-200 status codes
        if response.status_code != 200:
            warn('Request: {}; Status code: {}'.format(requests, response.status_code))

        # Break the loop if the number of requests is greater than expected
        if requests > 72:
            warn('Number of requests was greater than expected.')
            break

        # Parse the content of the request with BeautifulSoup
        page_html = BeautifulSoup(response.text, 'html.parser')

        # Select all the 50 movie containers from a single page
        mv_containers = page_html.find_all('div', class_ = 'lister-item mode-advanced')

        # For every movie of these 50
        for container in mv_containers:
            # If the movie has a Metascore, then:
            if container.find('div', class_ = 'ratings-metascore') is not None:

                # Scrape the name
                name = container.h3.a.text
                names.append(name)

                # Scrape the year
                year = container.h3.find('span', class_ = 'lister-item-year').text
                years.append(year)

                # Scrape the IMDB rating
                imdb = float(container.strong.text)
                imdb_ratings.append(imdb)

                # Scrape the Metascore
                m_score = container.find('span', class_ = 'metascore').text
                metascores.append(int(m_score))

                # Scrape the number of votes
                vote = container.find('span', attrs = {'name':'nv'})['data-value']
                votes.append(int(vote))

Request:12; Frequency: 0.081455316378573 requests/s

In [74]:
test_df = pd.DataFrame({'movie': names,
                        'year': years,
                        'imdb': imdb_ratings,
                        'votes': votes})
print(test_df.info())
test_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 556 entries, 0 to 555
Data columns (total 4 columns):
movie    556 non-null object
year     556 non-null object
imdb     556 non-null float64
votes    556 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 17.5+ KB
None

                      movie    year  imdb    votes
0                 Gladiator  (2000)   8.5  1284694
1                   Memento  (2000)   8.4  1079990
2                    Snatch  (2000)   8.3   754909
3       Requiem for a Dream  (2000)   8.3   736361
4                     X-Men  (2000)   7.4   555955
..                      ...     ...   ...      ...
551                  Hostel  (2005)   5.9   164689
552        The Longest Yard  (2005)   6.4   157138
553              Hard Candy  (2005)   7.1   150507
554              Flightplan  (2005)   6.3   148424
555  Green Street Hooligans  (2005)   7.5   138334

[556 rows x 4 columns]